FROM fedora:36

LABEL org.opencontainers.image.description="CI build image for Fedora (https://github.com/StoneStepsInc/fit)"

RUN dnf -y install cmake patch curl unzip make gcc-c++ sqlite-devel expat-devel zlib-devel

COPY get-exiv2 exiv2-c++17.patch /root/

WORKDIR /root

RUN chmod a+x get-sha256 get-exiv2

RUN ./get-sha256

RUN ./get-exiv2
