FROM ubuntu:22.04

LABEL org.opencontainers.image.description="CI build image for Ubuntu (https://github.com/StoneStepsInc/fit)"

RUN apt-get update -y

RUN apt-get install -y patch curl unzip make g++ libsqlite3-dev libexif-dev
