#!/bin/bash

PKG_VER=0.28.3
PKG_REV=%~1

EXIV2_FNAME=exiv2-$PKG_VER-Source.tar.gz
EXIV2_DNAME=exiv2-$PKG_VER
EXIV2_SHA256=1315e17d454bf4da3cc0edb857b1d2c143670f3485b537d0f946d9ed31d87b70

curl --location --output $EXIV2_FNAME https://github.com/Exiv2/exiv2/archive/refs/tags/v${PKG_VER}.tar.gz

echo "$EXIV2_SHA256  $EXIV2_FNAME" | sha256sum --check

if [ $? -ne 0 ]
then
    echo "Bad checksum: $EXIV2_FNAME"
    exit 1
fi

tar xzf $EXIV2_FNAME

rm -f $EXIV2_FNAME

patch -p1 --unified --directory $EXIV2_DNAME --input ../exiv2-suppress-warnings.patch

cmake -S $EXIV2_DNAME -B exiv2/Release \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=OFF \
    -DEXIV2_ENABLE_WEBREADY=OFF \
    -DEXIV2_ENABLE_CURL=OFF \
    -DEXIV2_ENABLE_BROTLI=OFF \
    -DEXIV2_ENABLE_INIH=OFF \
    -DEXIV2_ENABLE_VIDEO=ON \
    -DEXIV2_ENABLE_XMP=ON \
    -DEXIV2_BUILD_SAMPLES=OFF \
    -DEXIV2_BUILD_EXIV2_COMMAND=OFF \
    -DEXIV2_BUILD_UNIT_TESTS=OFF \
    -DEXIV2_BUILD_FUZZ_TESTS=OFF \
    -DEXIV2_ENABLE_PNG=ON \
    -DEXIV2_ENABLE_FILESYSTEM_ACCESS=ON

cmake --build exiv2/Release

cmake --install exiv2/Release

cp exiv2/Release/install_manifest.txt exiv2_install_manifest.txt

rm -rf exiv2/Release

rmdir exiv2

rm -rf $EXIV2_DNAME

