#!/bin/bash

GIT_COMMIT=5e637272c13f200872d55ff579f7e2ab6c3f252f

if [ -d src/sha256 ]
then
  echo Directory sha256 already exists
  exit
else 
  curl --location --output sha256.zip https://github.com/jb55/sha256.c/archive/$GIT_COMMIT.zip

  unzip sha256.zip
  rm -f sha256.zip

  mv sha256.c-$GIT_COMMIT src/sha256
  cd src/sha256

  mv deps/rotate-bits .

  rm -rf deps
  rm -f package.json rotate-bits/package.json
  rm -f .gitignore .travis.yml Makefile test.c

  cd ../..
fi
