name: Build CI images

on: workflow_dispatch

env:
  IMAGE_REG: ghcr.io
  # ghcr.io fails if owner is not lowercase - can't use `${{ github.actor }}`
  IMAGE_OWNER: stonestepsinc
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  build-ci-images:
    name: Build CI images
    runs-on: ubuntu-20.04
    strategy:
      matrix:
       linux-flavor:
       - fedora
       - ubuntu

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Build ${{ matrix.linux-flavor }} image
      run: |
        docker build --file devops/Dockerfile.${{ matrix.linux-flavor }} --tag ${{ env.IMAGE_REG }}/${{ env.IMAGE_OWNER }}/fit/${{ matrix.linux-flavor }}:${{ env.IMAGE_TAG }} devops

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ env.IMAGE_REG }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push ${{ matrix.linux-flavor }} image
      run: |
        docker push ${{ env.IMAGE_REG }}/${{ env.IMAGE_OWNER }}/fit/${{ matrix.linux-flavor }}:${{ env.IMAGE_TAG }}
