name: Build CI Images

on: workflow_dispatch

env:
  IMAGE_REG: ghcr.io
  IMAGE_OWNER: stonestepsinc
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  build-ci-image:
    name: Build CI image
    runs-on: ubuntu-20.04
    strategy:
      matrix:
       linux-flavor:
       - fedora

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Build CI image
      run: |
        docker build --file devops/Dockerfile.${{ matrix.linux-flavor }} --tag ${{ env.IMAGE_REG }}/${{ env.IMAGE_OWNER }}/fit-${{ matrix.linux-flavor }}:${{ env.IMAGE_TAG }} devops

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ env.IMAGE_REG }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push CI image
      run: |
        docker push ${{ env.IMAGE_REG }}/${{ env.IMAGE_OWNER }}/fit-${{ matrix.linux-flavor }}:${{ env.IMAGE_TAG }}
