
name: fit 0.1.0

on: workflow_dispatch

env:
  VERSION: 0.1.0
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build-fit:
    name: Build fit
    runs-on: windows-2019

    env:
      VCVARSALL: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall'

    defaults:
      run:
        shell: cmd
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Restore Nuget packages
      run: nuget restore

    - name: Set up SHA256
      run: get-sha256.bat

    - name: Build fit x64
      run: |
        call "${{ env.VCVARSALL }}" x64
        msbuild /nologo /target:Rebuild /property:Configuration=Release;Platform=x64;GH_BUILD_NUMBER=$(BUILD_NUMBER) /nr:false fit.vcxproj

    - name: Create fit package
      run: |
        mkdir fit-win64-${{ env.VERSION }}
        copy /y x64\Release\fit.exe fit-win64-${{ env.VERSION }}
        copy /y packages\StoneSteps.SQLite.Static.3.38.2.2\build\native\bin\sqlite3.exe fit-win64-${{ env.VERSION }}
        7z a fit-win64-${{ env.VERSION }}+${{ env.BUILD_NUMBER }}.zip fit-win64-${{ env.VERSION }}

    - name: Create a draft release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: fit-${{ env.VERSION }}
        draft: true

    - name: Upload fit-win64 package
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: fit-win64-${{ env.VERSION }}+${{ env.BUILD_NUMBER }}.zip
        asset_name: fit-win64-${{ env.VERSION }}+${{ env.BUILD_NUMBER }}.zip
        asset_content_type: application/zip
