#
# GitHub maintains the run number sequence per workflow file name,
# which means that this file needs to be renamed when the version
# is changed, so the run number starts a new sequence.
#
name: fit 1.0.2

on: workflow_dispatch

env:
  VERSION: 1.0.2
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build-windows:
    name: Windows build
    runs-on: windows-2019

    env:
      VCVARSALL: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall'

    defaults:
      run:
        shell: cmd
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Restore Nuget packages
      run: nuget restore

    - name: Set up SHA256 source
      run: get-sha256.bat

    - name: Build fit x64
      run: |
        call "${{ env.VCVARSALL }}" x64
        msbuild /nologo /target:Rebuild /property:Configuration=Release;Platform=x64;GH_BUILD_NUMBER=$(BUILD_NUMBER) /nr:false fit.vcxproj

      #
      # The only way to avoid hard-coded references to Nuget packages
      # is to build it as a VS project. Use the hard-coded version for
      # now and if SQLite gets updated more than expected, a dedicated
      # packaging VS project may be introduced into this solution.
      #
    - name: Create Windows package
      run: |
        mkdir fit-win64-${{ env.VERSION }}
        copy /y x64\Release\fit.exe fit-win64-${{ env.VERSION }}
        copy /y packages\StoneSteps.SQLite.Static.3.38.2.2\build\native\bin\sqlite3.exe fit-win64-${{ env.VERSION }}
        copy /y README.md fit-win64-${{ env.VERSION }}
        copy /y LICENSE. fit-win64-${{ env.VERSION }}
        7z a fit-win64-${{ env.VERSION }}+${{ env.BUILD_NUMBER }}.zip fit-win64-${{ env.VERSION }}

    - name: Upload Windows package
      uses: actions/upload-artifact@v2.2.1
      with:
        name: fit-win64-${{ env.VERSION }}
        path: fit-win64-${{ env.VERSION }}+${{ env.BUILD_NUMBER }}.zip

  build-linux:
    name: Linux build

    strategy:
      matrix:
       linux-flavor:
       - fedora

    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/stonestepsinc/fit-${{ matrix.linux-flavor }}:7

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Set up SHA-256
      run: |
        ./get-sha256

    - name: Build binaries
      run: |
        make GH_BUILD_NUMBER=${{ env.BUILD_NUMBER }}

    - name: Create ${{ matrix.linux-flavor }} package
      run: |
        mkdir fit-${{ matrix.linux-flavor }}-${{ env.VERSION }}
        cp build/fit fit-${{ matrix.linux-flavor }}-${{ env.VERSION }}
        cp README.md fit-${{ matrix.linux-flavor }}-${{ env.VERSION }}
        cp LICENSE fit-${{ matrix.linux-flavor }}-${{ env.VERSION }}
        tar czf fit-${{ matrix.linux-flavor }}-${{ env.VERSION }}+${{ env.BUILD_NUMBER }}.tar.gz fit-${{ matrix.linux-flavor }}-${{ env.VERSION }}

    - name: Upload ${{ matrix.linux-flavor }} package
      uses: actions/upload-artifact@v2.2.1
      with:
        name: fit-${{ matrix.linux-flavor }}-${{ env.VERSION }}
        path: fit-${{ matrix.linux-flavor }}-${{ env.VERSION }}+${{ env.BUILD_NUMBER }}.tar.gz

  create-draft-release:
    name: Create draft release
    runs-on: ubuntu-20.04
    needs: 
    - build-windows
    - build-linux

    outputs:
      draft-release-upload-url: ${{ steps.draft-release.outputs.upload_url }}

    steps:
    - name: Create a draft release
      id: draft-release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: fit-${{ env.VERSION }}
        draft: true

  upload-release-assets:
    name: Upload release assets
    runs-on: ubuntu-20.04

    needs:
    - create-draft-release

    strategy:
      matrix:
       build-flavor:
       - fedora
       - win64
       include:
       - build-flavor: fedora
         asset-content-type: application/gzip
         asset-ext: tar.gz
       - build-flavor: win64
         asset-content-type: application/zip
         asset-ext: zip

    steps:
    - name: Download ${{ matrix.build-flavor }} package
      uses: actions/download-artifact@v2.0.7
      with:
        name: fit-${{ matrix.build-flavor }}-${{ env.VERSION }}
        path: .

    - name: Add ${{ matrix.build-flavor }} package
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-draft-release.outputs.draft-release-upload-url }} 
        asset_path: fit-${{ matrix.build-flavor }}-${{ env.VERSION }}+${{ env.BUILD_NUMBER }}.${{ matrix.asset-ext }}
        asset_name: fit-${{ matrix.build-flavor }}-${{ env.VERSION }}+${{ env.BUILD_NUMBER }}.${{ matrix.asset-ext }}
        asset_content_type: ${{ matrix.asset-content-type }}
